# Generated by Django 4.2.1 on 2023-09-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.URLField(default='https://cdn1.iconfinder.com/data/icons/business-company-1/500/image-512.png', max_length=255),
        ),
    ]
